-- METROVALENCIA GENERAL DROP

DROP TABLE IF EXISTS METROVALENCIA.FGV_DATE_SERVICES, METROVALENCIA.FGV_LINES, METROVALENCIA.FGV_LINES_STATIONS, METROVALENCIA.FGV_NEXT_STATIONS, METROVALENCIA.FGV_SERVICES, METROVALENCIA.FGV_STATIONS, METROVALENCIA.FGV_TIMETABLES;

-- METROVALENCIA.FGV_LINES definition

-- Drop table

-- DROP TABLE METROVALENCIA.FGV_LINES;

CREATE TABLE IF NOT EXISTS METROVALENCIA.FGV_LINES (
	ID INTEGER NOT NULL,
	LINEA_ID_FGV INTEGER,
	NOMBRE_CORTO VARCHAR(100),
	NOMBRE_LARGO VARCHAR(1000),
	TIPO VARCHAR(100),
	COLOR VARCHAR(100),
	FORMA_ID INTEGER,
	SEDE VARCHAR(100),
	CREATED_AT VARCHAR(1000),
	UPDATED_AT VARCHAR(1000),
	DELETED_AT VARCHAR(1000),
	CONSTRAINT FGV_LINES_UN UNIQUE (ID)
);



-- METROVALENCIA.FGV_SERVICES definition

-- Drop table

-- DROP TABLE METROVALENCIA.FGV_SERVICES;

CREATE TABLE IF NOT EXISTS METROVALENCIA.FGV_SERVICES (
	ID INTEGER,
	SERVICIO_ID_FGV INTEGER,
	FECHA_INICIO_VALIDEZ DATE,
	FECHA_FIN_VALIDEZ DATE,
	DESCRIPCION VARCHAR(1000),
	DIAS_SEMANA VARCHAR(100),
	SEDE VARCHAR(100),
	CREATED_AT VARCHAR(100),
	UPDATED_AT VARCHAR(100),
	DELETED_AT VARCHAR(100),
	CONSTRAINT FGV_SERVICES_UN UNIQUE (ID)
);


-- METROVALENCIA.FGV_STATIONS definition

-- Drop table

-- DROP TABLE METROVALENCIA.FGV_STATIONS;

CREATE TABLE IF NOT EXISTS METROVALENCIA.FGV_STATIONS (
	ID INTEGER NOT NULL,
	ESTACION_ID_FGV INTEGER NOT NULL,
	WEB_ID INTEGER,
	NOMBRE VARCHAR(1000),
	TRANSBORDO VARCHAR(100),
	LATITUD DOUBLE,
	LONGITUD DOUBLE,
	DIRECCION VARCHAR(1000),
	SEDE VARCHAR(100),
	CREATED_AT VARCHAR(100),
	UPDATED_AT VARCHAR(100),
	DELETED_AT VARCHAR(100),
	CONSTRAINT FGV_STATIONS_UN UNIQUE (ID),
	CONSTRAINT FGV_STATIONS_UN_FGV UNIQUE (ESTACION_ID_FGV)
);


-- METROVALENCIA.FGV_DATE_SERVICES definition

-- Drop table

-- DROP TABLE METROVALENCIA.FGV_DATE_SERVICES;

CREATE TABLE IF NOT EXISTS METROVALENCIA.FGV_DATE_SERVICES (
	ID INTEGER,
	SERVICIO_ID INTEGER,
	FECHA DATE,
	SEDE VARCHAR(100),
	CREATED_AT VARCHAR(1000),
	UPDATED_AT VARCHAR(1000),
	DELETED_AT VARCHAR(1000));


-- METROVALENCIA.FGV_LINES_STATIONS definition

-- Drop table

-- DROP TABLE METROVALENCIA.FGV_LINES_STATIONS;

CREATE TABLE IF NOT EXISTS METROVALENCIA.FGV_LINES_STATIONS (
	ID_LINE INTEGER NOT NULL,
	ID_STATION INTEGER NOT NULL,
	CONSTRAINT FGV_LINES_STATIONS_FK_LINE FOREIGN KEY (ID_LINE) REFERENCES METROVALENCIA.FGV_LINES(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FGV_LINES_STATIONS_FK_STATION FOREIGN KEY (ID_STATION) REFERENCES METROVALENCIA.FGV_STATIONS(ESTACION_ID_FGV) ON DELETE RESTRICT ON UPDATE RESTRICT
);


-- METROVALENCIA.FGV_NEXT_STATIONS definition

-- Drop table

-- DROP TABLE METROVALENCIA.FGV_NEXT_STATIONS;

CREATE TABLE IF NOT EXISTS METROVALENCIA.FGV_NEXT_STATIONS (
	ID INTEGER,
	SERVICIO_ID INTEGER,
	ESTACION_ID INTEGER NOT NULL,
	ESTACION_SIGUIENTE_ID INTEGER NOT NULL,
	DISTANCIA_SIGUIENTE INTEGER,
	COSTE INTEGER,
	SEDE VARCHAR(100),
	CREATED_AT VARCHAR(100),
	UPDATED_AT VARCHAR(100),
	DELETED_AT VARCHAR(100),
	CONSTRAINT FGV_NEXT_STATIONS_FK FOREIGN KEY (ESTACION_ID) REFERENCES METROVALENCIA.FGV_STATIONS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FGV_NEXT_STATIONS_FK_1 FOREIGN KEY (ESTACION_SIGUIENTE_ID) REFERENCES METROVALENCIA.FGV_STATIONS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FGV_NEXT_STATIONS_FK_2 FOREIGN KEY (SERVICIO_ID) REFERENCES METROVALENCIA.FGV_SERVICES(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);


-- METROVALENCIA.FGV_TIMETABLES definition

-- Drop table

-- DROP TABLE METROVALENCIA.FGV_TIMETABLES;

CREATE TABLE IF NOT EXISTS METROVALENCIA.FGV_TIMETABLES (
	ORIGIN_STATION_ID INTEGER,
	DESTINATION_STATION_ID INTEGER,
	DEPARTURE_DATE DATE,
	DEPARTURE_TIME TIME,
	CONSTRAINT FGV_TIMETABLES_FK FOREIGN KEY (ORIGIN_STATION_ID) REFERENCES METROVALENCIA.FGV_STATIONS(ESTACION_ID_FGV) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FGV_TIMETABLES_FK_1 FOREIGN KEY (DESTINATION_STATION_ID) REFERENCES METROVALENCIA.FGV_STATIONS(ESTACION_ID_FGV) ON DELETE RESTRICT ON UPDATE RESTRICT
);


-- METROVALENCIA.BATCH_SERVICES_LOOKUP definition

-- Drop table

-- DROP TABLE METROVALENCIA.BATCH_SERVICES_LOOKUP;

CREATE TABLE IF NOT EXISTS METROVALENCIA.BATCH_SERVICES_LOOKUP (
    SERVICE_DATE DATE,
    LINE_ID INTEGER,
    JOB_INSTANCE_ID INTEGER,
    DATA_STORED BOOLEAN
);